
var sylls = [ { type: 'PROSODIC_CONTROL', symbol: '_' }, 
  { type: 'PHONEME', symbol: 's', phoneme_type: 'C' },
  { type: 'PROSODIC_CONTROL', symbol: '1' },
  { type: 'PHONEME', symbol: 'AE', phoneme_type: 'V' },
  { type: 'PHONEME', symbol: 'm', phoneme_type: 'C' },
  { type: 'PHONEME', symbol: 'y', phoneme_type: 'C' },
  { type: 'PHONEME', symbol: 'UW', phoneme_type: 'V' },
  { type: 'PHONEME', symbol: 'AX', phoneme_type: 'V' },
  { type: 'PHONEME', symbol: 'l', phoneme_type: 'C' },
  { type: 'PROSODIC_CONTROL', symbol: ' ' },
  { type: 'PROSODIC_CONTROL', symbol: '_' },
  { type: 'PHONEME', symbol: 's', phoneme_type: 'C' },
  { type: 'PHONEME', symbol: 't', phoneme_type: 'C' },
  { type: 'PROSODIC_CONTROL', symbol: '1' },
  { type: 'PHONEME', symbol: 'IY', phoneme_type: 'V' },
  { type: 'PHONEME', symbol: 'v', phoneme_type: 'C' },
  { type: 'PHONEME', symbol: 'IX', phoneme_type: 'V' },
  { type: 'PHONEME', symbol: 'n', phoneme_type: 'C' },
  { type: 'PHONEME', symbol: 'z', phoneme_type: 'C' },
  { type: 'PROSODIC_CONTROL', symbol: ' ' },
  { type: 'PROSODIC_CONTROL', symbol: '~' },
  { type: 'PHONEME', symbol: 'IH', phoneme_type: 'V' },
  { type: 'PHONEME', symbol: 'z', phoneme_type: 'C' },
  { type: 'PROSODIC_CONTROL', symbol: ' ' },
  { type: 'PROSODIC_CONTROL', symbol: '~' },
  { type: 'PHONEME', symbol: 'D', phoneme_type: 'C' },
  { type: 'PHONEME', symbol: 'AX', phoneme_type: 'V' },
  { type: 'PHONEME', symbol: 'r', phoneme_type: 'C' },
  { type: 'PROSODIC_CONTROL', symbol: ' ' },
  { type: 'PROSODIC_CONTROL', symbol: '_' },
  { type: 'PHONEME', symbol: 'r', phoneme_type: 'C' },
  { type: 'PROSODIC_CONTROL', symbol: '1' },
  { type: 'PHONEME', symbol: 'IY', phoneme_type: 'V' },
  { type: 'PHONEME', symbol: 'l', phoneme_type: 'C' },
  { type: 'PROSODIC_CONTROL', symbol: ' ' },
  { type: 'PROSODIC_CONTROL', symbol: '_' },
  { type: 'PHONEME', symbol: 'd', phoneme_type: 'C' },
  { type: 'PROSODIC_CONTROL', symbol: '1' },
  { type: 'PHONEME', symbol: 'IY', phoneme_type: 'V' },
  { type: 'PHONEME', symbol: 'l', phoneme_type: 'C' },
  { type: 'PROSODIC_CONTROL', symbol: ' ' },
  { type: 'PROSODIC_CONTROL', symbol: '_' },
  { type: 'PHONEME', symbol: 'AO', phoneme_type: 'V' },
  { type: 'PHONEME', symbol: 'r', phoneme_type: 'C' },
  { type: 'PHONEME', symbol: 'T', phoneme_type: 'C' },
  { type: 'PROSODIC_CONTROL', symbol: '1' },
  { type: 'PHONEME', symbol: 'AA', phoneme_type: 'V' },
  { type: 'PHONEME', symbol: 'g', phoneme_type: 'C' },
  { type: 'PHONEME', symbol: 'AX', phoneme_type: 'V' },
  { type: 'PHONEME', symbol: 'n', phoneme_type: 'C' },
  { type: 'PHONEME', symbol: 'AX', phoneme_type: 'V' },
  { type: 'PHONEME', symbol: 'l', phoneme_type: 'C' },
  { type: 'PROSODIC_CONTROL', symbol: '=' },
  { type: 'PHONEME', symbol: 'l', phoneme_type: 'C' },
  { type: 'PHONEME', symbol: 'IY', phoneme_type: 'V' },
  { type: 'PUNCTUATION_DATA', symbol: '.' } ];
module.exports = sylls;
